config/routes.rb
Rails.application.routes.draw do
  get '/artists', to: 'artists#index'
  get '/artists/:id', to:'artists#show', as: 'artist'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/testimony.rb
class Testimony < ApplicationRecord
  def self.pull_tweets
    $client.favorites('hellospiral', since_id: maximum(:tweet_id)).each do |tweet|
      unless exists?(tweet_id: tweet.id)
        create!(
          tweet_id: tweet.id,
          content: tweet.text,
          screen_name: tweet.user.screen_name,
        )
      end
    end
  end

  def testimony_params
    params.require(:testimony).permit(:tweet_id, :content, :screen_name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
   if !params[:artist_name].empty?
     @artists = RSpotify::Artist.search(params[:artist_name])
   else
     redirect_to root_path
   end
 end

  def show
    @artist = RSpotify::Artist.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @testimonies = Testimony.order("tweet_id desc").limit(5)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/artists/index.html.erb
<h1 class="page-header">Artists Matching <%= params[:artist_name] %></h1>

<ul>
 <% @artists.each do |artist| %>
   <li><%= artist.name %> | <%= artist.id %> | <%= link_to "Show", artist_path(artist.id) %></li>
 <% end %>
</ul>

app/views/artists/show.html.erb
<h1 class="page-header"><%= @artist.name %></h1>
<% @artist.albums(country: 'US').each do |album| %>
 <h3><%= album.name %></h3>
 <ul>
   <% album.tracks.each do |track| %>
     <li>
       <%= track.name %>
     </li>
   <% end %>
 </ul>
<% end %>

app/views/home/index.html.erb
<h1 class="page-header">Spotify Demo</h1>
<%= form_tag artists_path, method: "get", html: { class: "form" } do %>
 <div class="form-group col-xs-4">
   <%= text_field_tag(:artist_name, "", placeholder: "Enter artist name", class: "form-control") %>
 </div>
 <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

<h2>Recent favorited tweets:</h2>
<ul>
  <% @testimonies.each do |tweet| %>
    <li><%= tweet.screen_name %> - <%= tweet.content %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpotifyDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>